# TODO: Migrate to '.graphqlrc.json'
# See: https://github.com/prisma-labs/vscode-graphql/issues/142

schemaPath: ./server/prisma/schema.generated.graphql
extensions:
  endpoints:
    dev: http://localhost:4000/graphql
