[build]
  command   = 'yarn build'
  publish   = './client/public/'
  functions = './server/dist/functions/'

[build.environment]
  NODE_ENV = 'production'

[dev]
  command       = 'wsrun --no-prefix develop'
  targetPort    = 8000 # Depends on the Gatsby development server configuration
  port          = 8000 # Same as `targetPort`
  functionsPort = 4000 # Following the convention of GraphQL servers
  # TODO: Remove when https://github.com/netlify/cli/issues/624 gets resolved
  publish       = './client/public/'
