[build]
  command = 'yarn build'
  functions = './server/dist/functions/'
  publish = './client/public/'

[build.environment]
  NODE_ENV = 'production'

[dev]
  command = 'wsrun --no-prefix develop'
  port = 8000
  targetPort = 8000
  functionsPort = 4000
  # TODO: Remove when https://github.com/netlify/cli/issues/624 gets resolved
  publish = './client/public/'
