[build]
  command = "yarn build"
  functions = "server/build/functions/"
  publish = "client/public/"

[dev]
  command = "wsrun --no-prefix develop"
  port = 8000
  functionsPort = 4000
  targetPort = 8000
  publish = "client/public/"
